services:
  mongo:
    build:
      context: .
      args:
        MONGO_VERSION: 4
    environment:
      MONGO_REPLICA_HOST: 127.0.0.1
      MONGO_REPLICA_PORT: 27017
      MONGO_COMMAND: 'mongo'
    ports:
      - '27017:27017'
    restart: always
    # healthcheck:
    #   test:
    #     [
    #       'CMD',
    #       'mongo',
    #       'admin',
    #       '--port',
    #       '27017',
    #       '--eval',
    #       "db.adminCommand('ping').ok"
    #     ]
    #   interval: 5s
    #   timeout: 2s
    #   retries: 20
# version: '3.7'
# services:
#   mongodb_container:
#     # This image automatically creates a replica set required for transactions
#     image: prismagraphql/mongo-single-replica:4.4.3-bionic
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: root
#       MONGO_INITDB_ROOT_PASSWORD: prisma
#       INIT_WAIT_SEC: 3
#     ports:
#       - 27017:27017
